name: AntiSpam
version: '${project.version}'
main: com.github.distriful5061.antispam.antispam.AntiSpam
api-version: 1.18
authors: [ distriful5061 ]
website: https://github.com/distriful5061/AntiSpam
commands:
  menu:
    description: Menu Command

permissions:
  antispam.commands.menu:
    description: Menu Permission
    default: op